services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      # Important to bind/mount your codebase dir to /app dir for live reload
      - ./:/app
      - database:/app/pb_data

volumes:
  database:
