services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      # the http port
      - "80:80"
      # Web UI (enabled by api.insecure=true)
      - "8080:8080"
    volumes:
      # so that Traefik can listen to Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    image: ghcr.io/jedsonofnel/otterkin-web
    container_name: otterkin-web
    labels:
      - "traefik.http.routers.otterkin-web.rule=Host(`dev.otterkin.co.uk`)"
    volumes:
      - database:/pb_data

volumes:
  database:
